name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Lint & Security
        run: |
          bandit -r . -f txt -o bandit-report.txt || true
          flake8 . --count --statistics | tee flake8-report.txt
          safety scan --full-report | tee safety-report.txt || true

      - name: Tests
        run: pytest -q

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            bandit-report.txt
            flake8-report.txt
            safety-report.txt
