name: Defender for DevOps Scan

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  MSDO:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
      - name: Run Microsoft Security DevOps
        uses: microsoft/security-devops-action@v1.6.0
        id: msdo
      - name: Upload SARIF to Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}
