name: Deploy to Azure (safe smoke)

on:
  push:
    branches:
      - main
      - codex/**
      - copilot/**
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sanity
        run: echo "workflow ok"
