permissions:
  contents: read
name: Deploy Python App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checar el código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Configurar Python (aquí arreglamos el warning)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"   # Puedes fijar aquí la versión que uses en tu proyecto

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Correr tests (opcional pero recomendado)
      - name: Run tests
        run: |
          pytest || echo "No tests found, skipping..."

      # 5️⃣ Login en Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 6️⃣ Deploy a Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "NombreDeTuAppEnAzure"
          slot-name: "production"
          package: .

