name: OIDC Prod Smoke
on: { workflow_dispatch: {} }
permissions:
  id-token: write
  contents: read

jobs:
  prod-smoke:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Azure Login (env: prod, sin suscripción)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true

      - name: Get a token (proof)
        run: az account get-access-token --resource https://management.azure.com/ -o jsonc
