name: OIDC PR Smoke
on:
  pull_request:
    branches: [ "main" ]
permissions:
  id-token: write
  contents: read

jobs:
  pr-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login (PR subject)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true

      - name: Get a token (proof)
        run: az account get-access-token --resource https://management.azure.com/ -o jsonc
