permissions:
  contents: read
name: Función del sistema de procedencia

on:
  push:
    branches:
      - main

jobs:
  origen-sistema-funcion:
    runs-on: ubuntu-latest
    steps:
      - name: Repositorio checkout
        uses: actions/checkout@v4

      - name: Ejecutar función del sistema de procedencia
        run: python scripts/Python/funcion_del_sistema_de_procedencia.py

