name: SLSA Procedencia CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  provenance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generar procedencia SLSA
        uses: github/codeql-action/generate-slsa-provenance@v2
