name: Generar procedencia SLSA

on:
  push:
    branches: [main]
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: slsa-provenance-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  provenance:
    name: Build + SLSA provenance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build artifact (demo)
        run: |
          mkdir -p dist
          echo "Build $(date -Iseconds)" > dist/build.txt

      - name: Generar procedencia de compilación (archivo)
        id: gen
        uses: slsa-framework/slsa-github-generator/.github-hosted@v2.1.0
        with:
          subject-path: dist/build.txt

      - name: Cargar artefacto de procedencia SLSA
        uses: actions/upload-artifact@v4
        with:
          name: SLSA-Provenance
          path: ${{ steps.gen.outputs.provenance-path }}

      - name: Cargar artefacto de build
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist/build.txt

  security_scan:
    name: Microsoft Security DevOps scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python (3.11)
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run Microsoft Security DevOps
        uses: microsoft/security-devops-action@v1.6.0
        with:
          categories: "code,secrets,iac,containers"
          uploadSarif: true

  attest:
    name: Attestación (sólo en tags v*)
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: provenance
    permissions:
      attestations: write
      id-token: write
      contents: read
    steps:
      - name: Checkout (shallow)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Descargar artefacto de build
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: dist

      - name: Crear attestation de build
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: dist/build.txt
