name: SLSA Provenance v1

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  procedencia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build básico
        run: |
          mkdir -p dist
          echo "Compilación de ejemplo con SLSA" > dist/build.txt

      - name: Generar Procedencia
        uses: slsa-framework/slsa-github-generator/generator/javascript@v1
        with:
          artifact_path: ./dist

