name: Generate SLSA Provenance

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  provenance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Crea un artefacto de ejemplo; si ya tienes build real, usa tus propios archivos
      - name: Build artifact
        run: |
          mkdir -p dist
          echo "Build $(date -Iseconds)" > dist/build.txt

      # Genera archivo de provenance (.intoto.jsonl) con el SLSA generator
      - name: Generate Build Provenance (file)
        id: gen
        uses: slsa-framework/slsa-github-generator/.github-hosted@v2.0.0
        with:
          subject-path: dist/build.txt

      # Sube el archivo de provenance como artifact descargable
      - name: Upload SLSA Provenance artifact
        uses: actions/upload-artifact@v4
        with:
          name: slsa-provenance
          path: ${{ steps.gen.outputs.provenance-path }}

