name: Generate SLSA Provenance

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  attestations: write
  contents: read

jobs:
  generate-provenance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Paso de build: crea el archivo esperado por el paso de attestation
      - name: Build
        run: mkdir -p path/a/tu/archivo.o && touch path/a/tu/archivo.o/artefacto

      - name: Generate Build Provenance Attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: '${{ github.workspace }}/path/a/tu/archivo.o/artefacto'

      - name: Upload SLSA Provenance
        uses: actions/upload-artifact@v4
        with:
          name: slsa-provenance
          path: provenance.json
