name: SLSA Procedencia CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  provenance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Placeholder for provenance generation
        run: echo 'Skipping provenance generation - action unavailable'
