name: SLSA Procedencia CI

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  procedencia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generar procedencia
        uses: github/codeql-action/generate-slsa-provenance@v1
